import { app } from "../../scripts/app.js";
import { api } from "../../scripts/api.js";

const PROMPT_ID = "TerryH3PromptEditor";
const TIMELINE_ID = "TerryH3ShotTimeline";
const PROMPT_LINKS = "terry_h3_virtual_media_links";
const TIMELINE_LINKS = "terry_h3_timeline_virtual_media_links";
const BINDINGS_PROP = "terry_h3_subject_bindings";
const ROLE_PROP = "terry_h3_default_image_role";
const CARET = "\u200B";

const LANGUAGES = ["English","Chinese","Cantonese","Japanese","Korean","Spanish","French","German","Italian","Portuguese","Russian","Arabic","Hindi","Thai","Vietnamese","Indonesian","Turkish","Polish","Dutch","Other"];
const CATEGORY_META = [
  { id:"structure", label:"结构", icon:"§", detail:"H3 主字段与段落" },
  { id:"shot", label:"镜头", icon:"🎬", detail:"说话人与镜头辅助标签" },
  { id:"dialogue", label:"对白", icon:"💬", detail:"可编辑对白块与连续性" },
  { id:"retention", label:"保留关系", icon:"◎", detail:"视觉与音频引用关系" },
  { id:"task", label:"任务类型", icon:"▣", detail:"Summary 的任务类型前缀" },
  { id:"camera", label:"镜头运动", icon:"◉", detail:"Camera motion 常用表达" },
];

function nodeType(node){return String(node?.comfyClass||node?.type||node?.constructor?.comfyClass||node?.constructor?.type||node?.constructor?.nodeData?.name||"");}
function isTarget(node){const t=nodeType(node);return t===PROMPT_ID||t===TIMELINE_ID;}
function isTimeline(node){return nodeType(node)===TIMELINE_ID;}
function linksProp(node){return isTimeline(node)?TIMELINE_LINKS:PROMPT_LINKS;}
function links(node){node.properties||={};const v=node.properties[linksProp(node)];return Array.isArray(v)?v:[];}
function graphNode(id,node){return node?.graph?.getNodeById?.(Number(id))||app.graph?.getNodeById?.(Number(id))||null;}
function kindOf(src,slot,fallback=""){const t=String(src?.outputs?.[slot]?.type||fallback||"").toUpperCase();if(t.includes("AUDIO"))return"audio";if(t.includes("VIDEO"))return"video";return"picture";}
function filename(src,kind){const pref=kind==="picture"?["image","filename","file"]:kind==="video"?["video","file","filename","video_file","videofile"]:["audio","file","filename","audio_file","audiofile"];for(const w of src?.widgets||[]){const v=w?.value;const f=typeof v==="object"?(v?.filename||v?.name):v;if(!f||/^(data:|blob:|https?:)/i.test(String(f)))continue;if(pref.includes(String(w?.name||"").toLowerCase())||/\.(png|jpe?g|webp|gif|bmp|tiff?|mp4|webm|mov|mkv|avi|m4v|mp3|wav|flac|ogg|m4a|aac)$/i.test(String(f)))return String(f);}return"";}
function preview(src,kind){if(!src||kind==="audio")return"";const f=filename(src,kind);if(f){const w=(src.widgets||[]).find(x=>{const v=x?.value;return String(typeof v==="object"?(v?.filename||v?.name||""):(v||""))===f;});const v=w?.value;const q=new URLSearchParams({filename:f,type:typeof v==="object"?String(v.type||"input"):"input"});if(typeof v==="object"&&v.subfolder)q.set("subfolder",String(v.subfolder));return api.apiURL(`/view?${q.toString()}`);}return(src.imgs||[]).find(x=>x?.src)?.src||"";}
function assets(node){const count={picture:0,video:0,audio:0};const out=[];const seen=new Set();for(const link of links(node)){const id=Number(link?.source_id),slot=Number(link?.source_slot)||0,key=`${id}:${slot}`;if(!Number.isFinite(id)||seen.has(key))continue;const src=graphNode(id,node);if(!src)continue;seen.add(key);const kind=link.kind||kindOf(src,slot,link.source_type);count[kind]=(count[kind]||0)+1;const index=count[kind];const label=kind==="picture"?`Picture ${index}`:kind==="video"?`Video ${index}`:`Audio ${index}`;out.push({key,kind,index,label,raw:`<${label}>`,src,name:filename(src,kind).split(/[\\/]/).pop()||src.title||label,preview:preview(src,kind)});}return out;}
function findNodeForEditor(editor){for(const node of app.graph?._nodes||[]){if(!isTarget(node))continue;if(node.__terryH3Editor===editor)return node;if(node.__terryH3ShotTimeline?.root?.contains?.(editor))return node;}return null;}
function editorKind(editor){return editor?.classList?.contains("terry-tl-rich")?"timeline":"prompt";}
function closeLegacy(node){node?.__terryH3RoleMenu?.remove?.();node.__terryH3RoleMenu=null;node?.__terryH3CommandMenu?.remove?.();node.__terryH3CommandMenu=null;for(const m of document.querySelectorAll(".terry-tl-mention,.terry-h3-role-menu,.terry-h3-command-menu")){if(!m.__terryShared)m.remove();}}
function closeShared(){for(const m of document.querySelectorAll(".terry-h3-shared-menu"))m.remove();globalThis.__terryH3SharedState=null;}
function caretRange(editor,trigger){const s=window.getSelection?.();if(!s?.rangeCount||!s.isCollapsed)return null;const r=s.getRangeAt(0);if(!editor.contains(r.startContainer)||r.startContainer.nodeType!==Node.TEXT_NODE)return null;const before=String(r.startContainer.textContent||"").slice(0,r.startOffset);const esc=trigger==="@"?/@@?([^@\n]*)$/:/\/([^/\n]*)$/;const m=before.match(esc);if(!m)return null;const range=document.createRange();range.setStart(r.startContainer,r.startOffset-m[0].length);range.setEnd(r.startContainer,r.startOffset);return{range,query:String(m[1]||"").trim().toLowerCase()};}
function insertNodeAt(range,node,editor){range.deleteContents();const after=document.createTextNode(CARET);const frag=document.createDocumentFragment();frag.append(node,after);range.insertNode(frag);const s=window.getSelection?.();if(s){const r=document.createRange();r.setStart(after,after.textContent.length);r.collapse(true);s.removeAllRanges();s.addRange(r);}editor.dispatchEvent(new InputEvent("input",{bubbles:true,inputType:"insertText",data:null}));editor.focus({preventScroll:true});}
function simpleChip(editor,raw,label,kind=""){const el=document.createElement("span");el.contentEditable="false";el.dataset.raw=raw;if(editorKind(editor)==="timeline")el.className=`terry-tl-chip ${kind?`is-${kind}`:""}`;else el.className=`terry-h3-chip ${kind==="subject"?"terry-h3-subject-asset-chip terry-h3-strong":"terry-h3-media-chip"}`;el.textContent=label;return el;}
function promptText(node){const names=isTimeline(node)?["compiled_prompt","timeline_state"]:["prompt"];return names.map(n=>String(node?.widgets?.find(w=>w?.name===n)?.value||"")).join("\n");}
function bindings(node){node.properties||={};if(!node.properties[BINDINGS_PROP]||typeof node.properties[BINDINGS_PROP]!=="object"||Array.isArray(node.properties[BINDINGS_PROP]))node.properties[BINDINGS_PROP]={};return node.properties[BINDINGS_PROP];}
function nextSubject(node){const used=new Set();for(const m of promptText(node).matchAll(/<Subject\s+(\d+)>/gi))used.add(Number(m[1]));for(const list of Object.values(bindings(node)))for(const n of Array.isArray(list)?list:[])used.add(Number(n));let n=1;while(used.has(n))n++;return n;}
function subjectFor(node,a,fresh=false){const b=bindings(node);b[a.key]||=[];if(!fresh&&b[a.key][0])return Number(b[a.key][0]);const n=nextSubject(node);b[a.key].push(n);app.graph?.change?.();return n;}
function roleHelp(kind,role){if(role==="subject")return kind==="video"?"从视频中抽取人物、物体、场景、动作、表情或风格，作为后续镜头可复用的内容单元。":"从图片中抽取人物、物体、场景、服装、风格、动作或姿态，作为后续镜头可复用的内容单元。";if(role==="picture")return"直接引用这张图片本身：适合首帧、尾帧、关键帧、构图锚点或分镜规划。";if(role==="video")return"引用整段视频本身：适合视频编辑、续写、镜头运动、剪辑节奏或时间结构。";return"引用独立音频信号：适合完整/部分复用，或参考音色、节奏、对白、音乐与声音质感。";}
function button(text,title,cls=""){const b=document.createElement("button");b.type="button";b.className=`terry-h3-role-action ${cls}`;b.textContent=text;b.title=title;return b;}
function position(menu,editor,width=420,maxH=520){const s=window.getSelection?.();const c=s?.rangeCount?s.getRangeAt(0).getBoundingClientRect():null;const r=c&&(c.width||c.height)?c:editor.getBoundingClientRect();const h=Math.min(maxH,menu.offsetHeight||400);let l=r.left,t=r.bottom+6;if(l+width>innerWidth-8)l=innerWidth-width-8;if(t+h>innerHeight-8)t=Math.max(8,r.top-h-6);menu.style.left=`${Math.max(8,Math.round(l))}px`;menu.style.top=`${Math.max(8,Math.round(t))}px`;}
function openAsset(node,editor){const hit=caretRange(editor,"@");if(!hit)return false;closeLegacy(node);closeShared();const all=assets(node).filter(a=>!hit.query||`${a.name} ${a.label} ${a.kind}`.toLowerCase().includes(hit.query));const menu=document.createElement("div");menu.__terryShared=true;menu.className="terry-h3-role-menu terry-h3-shared-menu";document.body.append(menu);const role=node.properties?.[ROLE_PROP]==="picture"?"picture":"subject";const legend=document.createElement("div");legend.className="terry-h3-role-legend";const title=document.createElement("div");title.className="terry-h3-role-title";title.innerHTML="<b>引用角色</b><span>同一资产可以有不同 H3 角色</span>";const tabs=document.createElement("div");tabs.className="terry-h3-role-tabs";for(const [r,l] of [["subject","主体 · 内容"],["picture","画面 · 图片"]]){const b=button(l,roleHelp("picture",r),role===r?"is-active":"");b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();node.properties[ROLE_PROP]=r;app.graph?.change?.();openAsset(node,editor);};tabs.append(b);}const help=document.createElement("div");help.className="terry-h3-role-help";help.textContent=roleHelp("picture",role);legend.append(title,tabs,help);menu.append(legend);
for(const a of all){const row=document.createElement("div");row.className="terry-h3-role-row";const thumb=document.createElement("div");thumb.className=`terry-h3-role-thumb is-${a.kind}`;if(a.preview&&a.kind!=="audio"){const img=document.createElement("img");img.src=a.preview;thumb.append(img);}else thumb.textContent=a.kind==="audio"?"♪":a.kind==="video"?"▶":"▧";const info=document.createElement("div");info.className="terry-h3-role-info";const n=document.createElement("b");n.textContent=a.name;const meta=document.createElement("small");meta.textContent=a.kind==="picture"?`图片资产 · ${a.label}`:a.kind==="video"?`视频资产 · ${a.label}`:`音频资产 · ${a.label}`;info.append(n,meta);const actions=document.createElement("div");actions.className="terry-h3-role-actions";if(a.kind!=="audio"){const existing=bindings(node)[a.key]?.[0];const sb=button(existing?`Subject ${existing}`:"+ Subject",roleHelp(a.kind,"subject"),role==="subject"?"is-primary":"");sb.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const num=subjectFor(node,a,false);insertNodeAt(hit.range,simpleChip(editor,`<Subject ${num}>`,`Subject ${num}`,"subject"),editor);closeShared();};actions.append(sb);if(existing){const fresh=button("+ 新 Subject","同一资产里再定义一个独立 Subject","is-secondary");fresh.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const num=subjectFor(node,a,true);insertNodeAt(hit.range,simpleChip(editor,`<Subject ${num}>`,`Subject ${num}`,"subject"),editor);closeShared();};actions.append(fresh);}}
const direct=button(a.label,roleHelp(a.kind,a.kind),a.kind==="picture"&&role==="picture"?"is-primary":"");direct.onpointerdown=e=>{e.preventDefault();e.stopPropagation();const chip=simpleChip(editor,a.raw,a.label,a.kind);if(a.preview&&a.kind!=="audio"){const img=document.createElement("img");img.src=a.preview;img.alt="";chip.prepend(img);}insertNodeAt(hit.range,chip,editor);closeShared();};actions.append(direct);row.append(thumb,info,actions);menu.append(row);}if(!all.length){const empty=document.createElement("div");empty.className="terry-h3-role-empty";empty.textContent="没有匹配资产。先把图片 / 视频 / 音频连接到参考输入。";menu.append(empty);}position(menu,editor);globalThis.__terryH3SharedState={type:"asset",node,editor};return true;}

function nextSpeaker(node){let max=0;for(const m of promptText(node).matchAll(/\(S(\d+)\)/gi))max=Math.max(max,Number(m[1])||0);return max+1;}
function commands(node){const speaker=nextSpeaker(node);const list=[
{category:"structure",label:"subject_definitions",detail:"定义 Subject / Picture / Video / Audio 的引用角色",kind:"text",raw:"subject_definitions:"},{category:"structure",label:"summary",detail:"任务类型与主要引用关系摘要",kind:"text",raw:"summary:"},{category:"structure",label:"retention_analysis",detail:"逐项说明引用内容如何被保留或迁移",kind:"text",raw:"retention_analysis:"},{category:"structure",label:"detailed_description",detail:"逐镜头详细描述",kind:"text",raw:"detailed_description:"},{category:"structure",label:"integrated_multimodal_description",detail:"T2VA / I2VA / FL2VA / L2VA 主字段",kind:"text",raw:"integrated_multimodal_description:"},{category:"structure",label:"overall_soundscape",detail:"环境声、动作声与非语言人声汇总",kind:"text",raw:"overall_soundscape:"},{category:"structure",label:"non_diegetic_music",detail:"仅观众可听见的非剧情内音乐",kind:"text",raw:"non_diegetic_music:"},
{category:"shot",label:`Speaker S${speaker}`,detail:"插入下一个全局说话人编号",kind:"speaker",raw:`(S${speaker})`},
{category:"dialogue",label:"对白块",detail:"语言下拉 + 可直接编辑正文",kind:"dialogue",raw:"<d>[English] </d>"},{category:"dialogue",label:"scenetrans",detail:"对白或音频跨镜头连续",kind:"text",raw:"<scenetrans>"},{category:"dialogue",label:"cutoff",detail:"对白被视频结尾截断",kind:"text",raw:"<cutoff>"},
...[["fully_preserved","定义的视觉引用角色被完整保留"],["partially_preserved","仍使用引用内容，但部分特征被改变"],["attribute_transfer","把引用特征迁移到另一个可识别主体"],["weak_reference","仅保留宽泛风格、类别、构图或氛围"],["fully_copy","完整复制源音频信号"],["partially_copy","只复制部分时间或音频层"],["reference","只参考音色、节奏、内容或声音质感"]].map(([raw,detail])=>({category:"retention",label:raw,detail,kind:"text",raw})),
...[["reference generation","参考生成"],["keyframe completion","关键帧补全"],["video editing","直接编辑已有视频"],["video continuation","从已有视频继续生成"],["audio reuse","直接复用同一音频信号"],["audio reference","只参考音频特征而不复制信号"]].map(([raw,detail])=>({category:"task",label:raw,detail,kind:"text",raw:`[${raw}]`})),
...[["Push In","The camera pushes in "],["Pull Out","The camera pulls out "],["Pan Left","The camera pans left "],["Pan Right","The camera pans right "],["Truck Left","The camera trucks left "],["Truck Right","The camera trucks right "],["Tilt Up","The camera tilts up "],["Tilt Down","The camera tilts down "],["Pedestal Up","The camera moves upward "],["Pedestal Down","The camera moves downward "],["Arc Shot","The camera moves in an arc around the subject "],["Tracking Shot","The camera follows the moving subject in a tracking shot "],["Static Shot","The camera holds a static shot "],["Zoom In","The camera zooms in "],["Zoom Out","The camera zooms out "],["POV","POV, "],["Roll Clockwise","The camera rolls clockwise "],["Roll Counterclockwise","The camera rolls counterclockwise "],["Shake Slightly","The camera shakes slightly "],["Shake Strongly","The camera shakes strongly "]].map(([label,raw])=>({category:"camera",label,detail:raw.trim(),kind:"text",raw}))];return list;}
function cat(id){return CATEGORY_META.find(x=>x.id===id)||{id,label:id,icon:"›",detail:""};}
function openCommand(node,editor){const hit=caretRange(editor,"/");if(!hit)return false;closeLegacy(node);closeShared();let list=commands(node);if(hit.query)list=list.filter(c=>`${c.label} ${cat(c.category).label} ${c.detail} ${c.raw}`.toLowerCase().includes(hit.query));const state={type:"command",node,editor,range:hit.range,query:hit.query,category:null,active:0,options:[],menu:null};const menu=document.createElement("div");menu.__terryShared=true;menu.className="terry-h3-command-menu terry-h3-shared-menu";state.menu=menu;document.body.append(menu);globalThis.__terryH3SharedState=state;
const render=()=>{menu.replaceChildren();const search=Boolean(state.query);const head=document.createElement("div");head.className="terry-h3-command-head";const tw=document.createElement("div");tw.className="terry-h3-command-head-title";if(state.category&&!search){const back=document.createElement("button");back.type="button";back.className="terry-h3-command-back";back.textContent="‹";back.onpointerdown=e=>{e.preventDefault();state.category=null;state.active=0;render();};tw.append(back);}const h=document.createElement("b");h.textContent=search?"搜索 H3 语法":state.category?cat(state.category).label:"H3 语法";tw.append(h);const hint=document.createElement("span");hint.textContent=search?`“${state.query}”`:state.category?"← 返回 · ↑↓ 选择":"选择分类 · 也可继续输入关键词";head.append(tw,hint);menu.append(head);if(!state.category&&!search){state.options=CATEGORY_META.map(m=>({type:"category",meta:m,count:list.filter(c=>c.category===m.id).length})).filter(x=>x.count>0);}else{const rows=state.category&&!search?list.filter(c=>c.category===state.category):list;state.options=rows.map(command=>({type:"command",command}));}state.active=Math.min(state.active,Math.max(0,state.options.length-1));for(const [i,o] of state.options.entries()){const item=document.createElement("button");item.type="button";item.className=`terry-h3-command-item${i===state.active?" is-active":""}${o.type==="category"?" is-category":""}`;if(o.type==="category"){const icon=document.createElement("span");icon.className="terry-h3-command-category-icon";icon.textContent=o.meta.icon;const text=document.createElement("span");text.className="terry-h3-command-text";text.innerHTML=`<b>${o.meta.label}</b><small>${o.meta.detail}</small>`;const count=document.createElement("span");count.className="terry-h3-command-count";count.textContent=`${o.count} ›`;item.append(icon,text,count);item.onpointerdown=e=>{e.preventDefault();e.stopPropagation();state.category=o.meta.id;state.active=0;render();};}else{const label=document.createElement("span");label.className="terry-h3-command-category";label.textContent=cat(o.command.category).label;const text=document.createElement("span");text.className="terry-h3-command-text";text.innerHTML=`<b>${o.command.label}</b><small>${o.command.detail||o.command.raw}</small>`;item.append(label,text);item.onpointerdown=e=>{e.preventDefault();e.stopPropagation();chooseCommand(state,o.command);};}item.onpointermove=()=>{if(state.active!==i){state.active=i;render();}};menu.append(item);}position(menu,editor,320,340);};state.render=render;render();return true;}
function chooseCommand(state,c){const {editor,range}=state;range.deleteContents();let raw=c.raw||"";if(c.kind==="dialogue")raw="<d>[English] </d>";const node=simpleChip(editor,raw,c.kind==="speaker"?`🎙 ${raw.slice(1,-1)}`:c.kind==="dialogue"?"Dialogue":raw.replaceAll("_"," "),c.kind==="speaker"?"speaker":c.kind==="dialogue"?"dialogue":"");insertNodeAt(range,node,editor);closeShared();}
function handleKey(e){const s=globalThis.__terryH3SharedState;if(!s||s.type!=="command"||s.editor!==e.target)return false;if(e.key==="Escape"){closeShared();return true;}if(e.key==="ArrowLeft"&&s.category&&!s.query){s.category=null;s.active=0;s.render();return true;}if(e.key==="ArrowDown"||e.key==="ArrowUp"){if(s.options.length){s.active=(s.active+(e.key==="ArrowDown"?1:-1)+s.options.length)%s.options.length;s.render();s.menu.querySelector(".is-active")?.scrollIntoView?.({block:"nearest"});}return true;}if(["ArrowRight","Enter","Tab"].includes(e.key)){const o=s.options[s.active];if(!o)return false;if(o.type==="category"){s.category=o.meta.id;s.active=0;s.render();}else chooseCommand(s,o.command);return true;}return false;}

function schedule(editor,trigger){setTimeout(()=>{const node=findNodeForEditor(editor);if(!node)return;closeLegacy(node);trigger==="@"?openAsset(node,editor):openCommand(node,editor);},0);}
function install(){if(globalThis.__terryH3SharedMenusInstalled)return;globalThis.__terryH3SharedMenusInstalled=true;document.addEventListener("beforeinput",e=>{const editor=e.target?.closest?.(".terry-h3-editor,.terry-tl-rich");if(!editor)return;if(e.inputType==="insertText"&&e.data==="@")schedule(editor,"@");if(e.inputType==="insertText"&&e.data==="/")schedule(editor,"/");},true);document.addEventListener("input",e=>{const editor=e.target?.closest?.(".terry-h3-editor,.terry-tl-rich");const s=globalThis.__terryH3SharedState;if(!editor||!s||s.editor!==editor)return;queueMicrotask(()=>{closeLegacy(s.node);if(s.type==="asset")openAsset(s.node,editor);else openCommand(s.node,editor);});},true);document.addEventListener("keydown",e=>{if(handleKey(e)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();}},true);document.addEventListener("pointerdown",e=>{if(e.target.closest?.(".terry-h3-shared-menu"))return;const s=globalThis.__terryH3SharedState;if(s&&!s.editor?.contains?.(e.target))closeShared();},true);}

app.registerExtension({name:"TerryToolbox.H3SharedMenus",setup(){install();},afterConfigureGraph(){install();}});
